services:
  app:
    image: gerroldk/simple-web
    ports:
      - "8000:5000"
    volumes:
      - ./config:/config

  nginx:
    image: gerroldk/simple-nginx
    ports:
      - "80:80"
    depends_on:
      - app



